[package]
name = "protocols"
version = "0.0.1"
authors = ["James Prince <34577138+zutils@users.noreply.github.com>"]
repository = "https://github.com/zutils/protocols"
keywords = ["protocol"]
categories = ["parser-implementations", "rust-patterns", "template-engine", "web-programming"]
description = "The protocols crate is native rust library that provides an application layer system designed to make it easy to send messages between systems"
readme = "./README.md"
license = "MIT/Apache-2.0"

[dependencies]
failure = "0.1.3"
signals = "0.0.2"
libloading = "0.5"
notify = "4.0.6"
glob = "0.2"
serde = "1.0.80"
serde_json = "1.0.32"
protobuf-codegen = "2.1.2"
protobuf-codegen-pure = "2.1.2"
ipfs-api = "0.5.0-alpha2"
hyper = "0.12.13"
toml = "0.4.8"
toml-query = "0.7.0"
rand = "*"

[badges]
travis-ci = { repository = "zutils/protocols" }
