[package]
name = "protocols"
version = "0.0.1"
authors = ["James Prince <34577138+zutils@users.noreply.github.com>"]
repository = "https://github.com/zutils/protocols"
keywords = ["protocol"]
categories = ["parser-implementations", "rust-patterns", "template-engine", "web-programming"]
description = "The protocols crate is native rust library that provides an application layer system designed to make it easy to send messages between systems"
readme = "./README.md"
license = "MIT/Apache-2.0"

[dependencies]
failure = "0.1.3"
signals = "*"
libloading = "0.5"
notify = "4.0.6"
glob = "0.2"
serde = "*"
serde_json = "*"
