[package]
name = "protocols"
version = "0.0.5"
authors = ["James Prince <34577138+zutils@users.noreply.github.com>"]
repository = "https://github.com/zutils/protocols"
keywords = ["protocol"]
categories = ["parser-implementations", "rust-patterns", "template-engine", "web-programming"]
description = "The protocols crate is native rust library that provides an application layer system designed to make it easy to send messages between systems"
readme = "./README.md"
license = "MIT/Apache-2.0"
build = "./src/build.rs"
edition = "2018"

[dependencies]
failure = "0.1.3"
signals = "0.0.5"
libloading = "0.5"
notify = "4.0.6"
glob = "0.2"
protobuf = "2.2.0"
protobuf-codegen = "2.2.0"
protobuf-codegen-pure = "2.2.0"
protoc-rust-grpc = "0.6.1"
pb-rs = "0.7.0"
ipfs-api = "0.5.0-alpha2"
hyper = "0.12.18"
rand = "0.6.1"

[build-dependencies]
failure = "0.1.3"
protoc-rust-grpc = "0.6.1"
protobuf-codegen-pure = "2.2.0"
hyper = "0.12.18"
ipfs-api = "0.5.0-alpha2"

[badges]
travis-ci = { repository = "zutils/protocols" }
