[package]
name = "test-protocol"
version = "0.1.0"
authors = ["James Prince <34577138+zutils@users.noreply.github.com>"]

[dependencies]
protobuf = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"
failure = "*"
protocols = { path = "../../" }


[build-dependencies]
failure = "0.1.2"
protocols = { path = "../../" }

[features]
with-serde = ["protobuf/with-serde"]
default = ["with-serde"]

[lib]
crate-type = ["dylib"]
